# Generated by Django 4.2.6 on 2023-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("contact", models.IntegerField()),
                ("email", models.EmailField(max_length=50)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
